const limits = {
    rolecreatelimit: 'RoleCreateLimites',
    roleupdatelimit: 'RoleUpdateLimites',
    roledeletelimit: 'RoleDeleteLimites',
    channelcreatelimit: 'ChannelCreateLimites',
    channelupdatelimit: 'ChannelUpdateLimites',
    channeldeletelimit: 'ChannelDeleteLimites',
    emojicreatelimit: 'EmojiCreateLimites',
    emojideletelimit: 'EmojiDeleteLimites',
    emojiupdatelimit: 'EmojiUpdateLimites',
    stickercreatelimit: 'StickerCreateLimites',
    stickerdeletelimit: 'StickerDeleteLimites',
    stickerupdatelimit: 'StickerUpdateLimites',
    memberbanlimit: 'MemberBanLimites',
    memberkicklimit: 'MemberKickLimites',
    memberunbanlimit: 'MemberUnbanLimites',
    webhookcreatelimit: 'WebhookCreateLimites',
    webhookupdatelimit: 'WebhookUpdateLimites',
    webhookdeletelimit: 'WebhookDeleteLimites',
  };